; Addresses
.define MSU_EXISTS $0000
.define CURR_TRACK $0001
.define CURR_VOLUME $0002
.define STATUS_COLORL $0003
.define STATUS_COLORH $0004
.define TEMPA $0010
.define TEMPX $0011     

; Values
.define ERR_UNKNOWN $00
.define ERR_NOMSU $01
.define ERR_BADTRACK $02

; Brute Force Palette
.define RED_L     %00011111
.define RED_H     %00000000
.define YELLOW_L  %11111111
.define YELLOW_H  %00000011
.define GREEN_L   %11100000
.define GREEN_H   %00000011
.define CYAN_L    %11100000
.define CYAN_H    %01111111
.define BLUE_L    %00000000
.define BLUE_H    %01111100
.define MAGENTA_L %00011111
.define MAGENTA_H %01111100
.define WHITE_L   %11111111
.define WHITE_H   %01111111


